### ISSUE TITLE
CLI doesn't work 

### ISSUE THREAD

**Issue by Yokann** [thelia/thelia-project#20]
Hello,

When i type 

```
php Thelia thelia:install 
```

prompt print me the content of bin/Thelia : 

```
unix:~$ php Thelia thelia:install 
#!/usr/bin/env sh
SRC_DIR="`pwd`"
cd "`dirname "$0"`"
cd "../vendor/thelia/core"
BIN_TARGET="`pwd`/Thelia"
cd "$SRC_DIR"
"$BIN_TARGET" "$@" 
```

In root_project/Thelia , i found this line 

```
require 'bin/Thelia';
```

I never seen that before, call a shell script directly with php. Is it really works ?

I'm using Thelia 2.2 wityh PHP5.6.

**Comment by Yokann** [comment]
I propose to replace this line with this 
```
include __DIR__ . DIRECTORY_SEPARATOR.'vendor'. DIRECTORY_SEPARATOR.'thelia'. DIRECTORY_SEPARATOR.'core'. DIRECTORY_SEPARATOR.'Thelia';
```

It seems to be good

**Comment by lunika** [comment]
There is nothing wrong. Composer will create a symlink from  `bin/Thelia` to `vendor/thelia/core/lib/Thelia/Thelia`

**Comment by Yokann** [comment]
Thank you, but it still not working. 

Prompt still continue to show me `bin/Thelia` content when i type 
```
php Thelia thelia:install 
```

**Comment by lunika** [comment]
I didn't notice before but the content of `bin/Thelia` is not the good one, the goos content is this one : https://github.com/thelia/core/blob/2.2.0/Thelia

But where come from your content... I have no idea, it's weird.

**Comment by Yokann** [comment]
When you create project with composer : 
Composer install a bin directory at the root of the project with a file named Thelia which i think should be a link but in fact is a shell script.

I think composer fails to do the link and return shell code into this file.

Pardonnez mon français :)
